################################################################################################################## G E T
GET https://vacancies-jdbc-spring.herokuapp.com/vacancies/
###
GET https://vacancies-jdbc-spring.herokuapp.com/vacancies/21
###
GET https://vacancies-jdbc-spring.herokuapp.com/vacancies/ids?id=2&id=1&id=22&id=21
################################################################################################################### FIND
https://vacancies-jdbc-spring.herokuapp.com/vacancies/find?sal=100000&sort=2
###
http://vacancies-jdbc-spring.herokuapp.com/vacancies/find?date=2020-12-01
###
http://vacancies-jdbc-spring.herokuapp.com/vacancies/find?names=MANGO OFFICE&names=Автошкола СВЕТОФОР
###
http://vacancies-jdbc-spring.herokuapp.com/vacancies/find?comps=6&comps=4
###
http://vacancies-jdbc-spring.herokuapp.com/vacancies/find?locs=1001&rows=10&sort=2
###
http://vacancies-jdbc-spring.herokuapp.com/vacancies/find?rates=3
###
http://vacancies-jdbc-spring.herokuapp.com/vacancies/find?profs=2
###
http://vacancies-jdbc-spring.herokuapp.com/vacancies/find?empls=4
###
http://vacancies-jdbc-spring.herokuapp.com/vacancies/find?langs=2&langs=3
###
http://vacancies-jdbc-spring.herokuapp.com/vacancies/find?ctgrs=2
###
http://vacancies-jdbc-spring.herokuapp.com/vacancies/find?types=2
###
http://vacancies-jdbc-spring.herokuapp.com/vacancies/find?page=4&sort=-2
################################################################################################################### SAVE
POST http://vacancies-jdbc-spring.herokuapp.com/vacancies
Content-Type: application/json

{
  "id": 0,
  "name": "Администратор/продавец в магазин детской одежды",
  "date": "2020-12-01",
  "salaryMin": 20000,
  "salaryMax": 40000,
  "rate_id" : 1,
  "location_id": 1000004,
  "company_id" : 12,
  "types_ids" : [1],
  "professions_ids" : [5001, 6001],
  "employments_ids" : [1],
  "categories_ids" : [],
  "levels_languages_ids" : [[],[]]
}
###
POST http://vacancies-jdbc-spring.herokuapp.com/vacancies
Content-Type: application/json

{
  "id": 21,
  "name": "Водитель экспедитор",
  "salaryMin": 70000,
  "salaryMax": 80000,
  "rate_id" : 1,
  "location_id": 1000003,
  "company_id" : 11,
  "types_ids" : [1],
  "professions_ids" : [3001, 3002],
  "employments_ids" : [1],
  "categories_ids" : [3, 5]
}
###
POST http://vacancies-jdbc-spring.herokuapp.com/vacancies
Content-Type: application/json

{
  "id": 0,
  "name": "Репетитор по английскому и немецкому языкам",
  "salaryMin": 1200,
  "salaryMax": 1200,
  "rate_id" : 3,
  "location_id": 1000003,
  "types_ids" : [1, 2],
  "professions_ids" : [2001],
  "employments_ids" : [2],
  "languages_ids_levels_ids" : [[1,2],[2,3]]
}

################################################################################################################# REMOVE
DELETE http://vacancies-jdbc-spring.herokuapp.com/vacancies/21/remove
########################################################################################################################