################################################################################################################## G E T
GET http://localhost:8080/vacancies
###
GET http://localhost:8080/vacancies/20
###
GET http://localhost:8080/vacancies/ids?id=3&id=1&id=21
################################################################################################################### FIND
http://localhost:8080/vacancies/find?names=1с&names=  jaVa   &names="  ПРЕПОДАВАТАЕЛЬ"&names=          ПРЕП
###
http://localhost:8080/vacancies/find?names=рарус&rows=150
###
http://localhost:8080/vacancies/find?locs=1&profs=2001&rows=3&sort=2&page=3
###
http://localhost:8080/vacancies/find?ctgrs=4&ctgrs=2&ctgrs=3&sort=2
###
http://localhost:8080/vacancies/find?rates=3&rates=1
###
http://localhost:8080/vacancies/find?sal=50001&locs=1001
###
http://localhost:8080/vacancies/find?profs=3002
###
http://localhost:8080/vacancies/find?names=1с&names=java&rows=3&page=2
###
http://localhost:8080/vacancies/find?langs=1
###
http://localhost:8080/vacancies/find?page=4
################################################################################################################### SAVE
POST http://localhost:8080/vacancies
Content-Type: application/json

{
  "id": 0,
  "name": "Администратор/продавец в магазин детской одежды",
  "date": "2020-12-01",
  "salaryMin": 20000,
  "salaryMax": 40000,
  "rate_id" : 1,
  "location_id": 1000004,
  "company_id" : 12,
  "types_ids" : [1],
  "professions_ids" : [5001, 6001],
  "employments_ids" : [1],
  "categories_ids" : [],
  "levels_languages_ids" : [[],[]]
}
###
POST http://localhost:8080/vacancies
Content-Type: application/json

{
  "id": 0,
  "name": "Водитель экспедитор",
  "salaryMin": 70000,
  "salaryMax": 80000,
  "rate_id" : 1,
  "location_id": 1000003,
  "company_id" : 11,
  "types_ids" : [1],
  "professions_ids" : [3001, 3002],
  "employments_ids" : [1],
  "categories_ids" : [3, 5]
}
###
POST http://localhost:8080/vacancies
Content-Type: application/json

{
  "id": 0,
  "name": "Репетитор по англискому и немецкому языкам",
  "salaryMin": 1200,
  "salaryMax": 1200,
  "rate_id" : 3,
  "location_id": 1000003,
  "types_ids" : [1, 2],
  "professions_ids" : [2001],
  "employments_ids" : [2],
  "languages_ids_levels_ids" : [[1,2],[2,3]]
}

################################################################################################################# REMOVE
DELETE http://localhost:8080/vacancies/18/remove
########################################################################################################################